# pesigitg sysctl configuration
#
# For interface specific configuration uncomment and adjust these two lines
#net.ipv4.conf.eth0.arp_ignore = 1
#net.ipv4.conf.eth0.arp_announce = 2
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2

# Suppress IPv6 NS DAD on loopback, a no-op, but if managing VIPs at runtime the
# disabing of DAD would allow for zero transition delay.
#net.ipv6.conf.lo.accept_dad = 0
