[workspace]
resolver = "2"
members = ["pesigitg-daemon", "pesigitg-common", "xtask"]
exclude = ["pesigitg-ebpf"]
default-members = ["pesigitg-daemon", "pesigitg-common"]

[profile.release]
opt-level = 3
lto = true        # link-time optimization across crates
codegen-units = 1 # slower compile, but better optimization
panic = "abort"   # no unwinding overhead in the fast path
strip = "symbols" # smaller binary, slight startup benefit
