[package]
name = "pesigitg-daemon"
version = "0.1.0"
edition = "2021"
description = "A QUIC-aware load balancer"

[[bin]]
name = "pesigitgd"
path = "src/main.rs"

[dependencies]
pesigitg-common = { path = "../pesigitg-common", features = ["std"] }

anyhow = "1"
env_logger = "0.11"
log = "0.4"
nix = { version = "0.31", features = ["fs", "process", "signal"] }
pico-args = "0.5"
sd-notify = "0.4"
signal-hook = "0.4"
syslog = "7"
libc = "0.2"
bytesize = "2.3"

[build-dependencies]
chrono = "0.4"
