[package]
name = "pesigitg-daemon"
version = "0.1.0"
edition = "2024"
description = "A high-performance QUIC-aware load balancer, using eBPF and AF_XDP for kernel-bypass packet forwarding."

[[bin]]
name = "pesigitgd"
path = "src/main.rs"

[dependencies]
pesigitg-common = { path = "../pesigitg-common", features = ["std"] }

aya = "0.13"
aya-log = "0.2"
aes = "0.8"
anyhow = "1"
env_logger = "0.11"
log = "0.4"
nix = { version = "0.31", features = ["fs", "process", "sched", "signal"] }
pico-args = "0.5"
sd-notify = "0.4"
signal-hook = "0.4"
syslog = "7"
libc = "0.2"
bytesize = "2.3"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[build-dependencies]
chrono = "0.4"
